name: Push actions

on:
  push:
    branches:
      - master
      - dev

jobs:
  checkout:
    runs-on: "ubuntu-latest"
    name: Checkout validation
    steps:
        - uses: "actions/checkout@v2"

  hacs:
    runs-on: "ubuntu-latest"
    name: HACS validation
    steps:
        - name: HACS validation
          uses: "hacs/action@main"
          with:
            category: "integration"
            ignore: brands

  hassfest:
    runs-on: "ubuntu-latest"
    name: Hassfest validation
    steps:
        - name: Hassfest validation
          uses: "home-assistant/actions/hassfest@master"

  style:
    runs-on: "ubuntu-latest"
    name: Check style formatting
    steps:
        - uses: "actions/checkout@v2"
        - uses: "actions/setup-python@v1"
          with:
            python-version: "3.x"
        - run: python3 -m pip install black
        - run: black .

  tests:
    runs-on: "ubuntu-latest"
    name: Run tests
    steps:
      - name: Check out code from GitHub
        uses: "actions/checkout@v2"
      - name: Setup Python
        uses: "actions/setup-python@v1"
        with:
          python-version: "3.8"
      - name: Install requirements
        run: python3 -m pip install -r requirements_test.txt
      - name: Run tests
        run: |
          pytest \
            -qq \
            --timeout=9 \
            --durations=10 \
            -n auto \
            --cov custom_components.dremel_3d_printer \
            -o console_output_style=count \
            -p no:sugar \
            tests